---
kind: pipeline
type: docker
name: gazetteer

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

steps:

  - name: build
    image: committed/ci:1.6.0
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - mvn -B clean package
    

  - name: dockerhub
    image: committed/ci:1.6.0
    environment:
      DOCKERHUB_USERNAME:
        from_secret: dockerhub_username
      DOCKERHUB_PASSWORD:
        from_secret: dockerhub_password
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - mvn -B dockerfile:build
      - mvn -B dockerfile:tag@tag-version
      - mvn -B dockerfile:push@push-latest -Ddockerfile.username=$DOCKERHUB_USERNAME -Ddockerfile.password=$DOCKERHUB_PASSWORD
      - mvn -B dockerfile:push@push-version -Ddockerfile.username=$DOCKERHUB_USERNAME -Ddockerfile.password=$DOCKERHUB_PASSWORD
    when:
      ref:
        - refs/tags/v*
      
  - name: slack
    image: plugins/slack
    settings:
      channel: group-ci
      webhook:
        from_secret: slack_webhook
      template:
        from_secret: slack_template
    when:
      status:
        - failure

  - name: announce
    image: plugins/slack
    settings:
      channel: group-dev
      webhook:
        from_secret: slack_webhook
      template: >
        :tada: New version ${DRONE_TAG} of `committed/gazetteer` available
    when:
      ref:
        - refs/tags/v*
      status:
        - success