logging:
  level:
    io:
      committed: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:gazatteerdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1

# CUSTOM CONFIGURATION OPTIONS
# gazetter:
#   backup:
#     timeout: 60