server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    hibernate:
      dll-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:/data/gazetteer
    username: sa
    password:

logging:
  level: INFO
